title: Sustainable Development
description: >-
  Sustainable Development: software engineering done healthily, ethically, and for the long term.
baseurl: ""
url: "https://sustainabledev.org"
twitter_username: brikelly
github_username:  brikelly

# Build settings
markdown: kramdown
theme: minima

sass:
  sass_dir: _sass

include: ['_pages']

kramdown:
  input: GFM
